/*
 * Turns `.next/standalone` into something that can actually be run.
 *
 * Next traces the server and its dependencies there but deliberately leaves
 * out the two things it can't know the deployment shape of: the static assets
 * and anything from public/. electron-builder copies the finished directory
 * into the app's resources, so it has to be complete before packaging.
 */

import { access, cp, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const standalone = path.join(root, ".next", "standalone");

const exists = (p) => access(p).then(() => true, () => false);

async function main() {
  if (!(await exists(standalone))) {
    throw new Error(
      'No .next/standalone — run "next build" with output: "standalone" in next.config.mjs first.'
    );
  }

  await cp(path.join(root, ".next", "static"), path.join(standalone, ".next", "static"), {
    recursive: true,
  });

  if (await exists(path.join(root, "public"))) {
    await cp(path.join(root, "public"), path.join(standalone, "public"), { recursive: true });
  }

  await writeEnv();

  console.log("[prepare-desktop] .next/standalone is ready to package");
}

/*
 * Next inlines NEXT_PUBLIC_* at build time, but middleware and the route
 * handlers read process.env at request time too, so the bundled server gets
 * its own .env.production. Only NEXT_PUBLIC_* keys are copied — those are
 * public by definition (they already ship inside the client bundle), and the
 * filter keeps any private key in .env.local from being packaged by accident.
 */
async function writeEnv() {
  const fromFile = {};
  const envLocal = path.join(root, ".env.local");

  if (await exists(envLocal)) {
    for (const line of (await readFile(envLocal, "utf8")).split("\n")) {
      const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
      if (match) fromFile[match[1]] = match[2].trim().replace(/^["']|["']$/g, "");
    }
  }

  const merged = { ...fromFile, ...process.env };
  const publicKeys = Object.keys(merged)
    .filter((key) => key.startsWith("NEXT_PUBLIC_"))
    .sort();

  if (!publicKeys.includes("NEXT_PUBLIC_SUPABASE_URL")) {
    console.warn(
      "[prepare-desktop] NEXT_PUBLIC_SUPABASE_URL is not set — the packaged app will not be able to sign anyone in."
    );
  }

  await writeFile(
    path.join(standalone, ".env.production"),
    `# Generated by scripts/prepare-desktop.mjs — do not edit.\n` +
      publicKeys.map((key) => `${key}=${merged[key]}`).join("\n") +
      "\n",
    "utf8"
  );

  console.log(`[prepare-desktop] wrote ${publicKeys.length} NEXT_PUBLIC_* vars into the bundle`);
}

main().catch((error) => {
  console.error(`[prepare-desktop] ${error.message}`);
  process.exit(1);
});
